export const actionTypes = {
  LOAD_SUNGLASSES: 'LOAD_SUNGLASSES'
}

export const mutationTypes = {
  UPDATE_SUNGLASSES_LIST: 'UPDATE_SUNGLASSES_LIST',
  ADD_TO_SHOPPING_CART: 'ADD_TO_SHOPPING_CART',
  REMOVE_FROM_SHOPPING_CART: 'REMOVE_FROM_SHOPPING_CART'
}

export const getterTypes = {
  SUNGLASSES_LIST: 'SUNGLASSES_LIST',
  SHOPPING_CART_LIST: 'SHOPPING_CART_LIST'
}
